version: "3.3"

services:
  edumeet:
    build: .
    env_file: .env
    command: node ${BASEDIR}/${EDUMEET}/server/server.js
    depends_on: 
      - redis
    restart: unless-stopped
    volumes:
      - ./configs/server:${BASEDIR}/${EDUMEET}/server/config
      - ./configs/app:${BASEDIR}/${EDUMEET}/server/public/config
      - ./certs:${BASEDIR}/${EDUMEET}/server/certs
      - ./images:${BASEDIR}/${EDUMEET}/server/public/images
      - ./privacy:${BASEDIR}/${EDUMEET}/server/public/static/privacy
      - ./.well-known:${BASEDIR}/${EDUMEET}/server/public/.well-known
    ports:
      - "80:80"
      - "443:443"
      - "40000-49999:40000-49999/udp"
    network_mode: "host"
    stdin_open: true
    tty: true
    container_name: edumeet

  redis:
    image: redis
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ./configs/redis:/usr/local/etc/redis

  coturn:
    image: instrumentisto/coturn
    network_mode: "host"
    stop_signal: SIGKILL
    restart: unless-stopped
    volumes:
     - ./coturn.conf:/etc/coturn/turnserver.conf

  exporter:
    image: 'marckhouzam/custom-prometheus-exporter'
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './exporter-config.yml:/edumeet-exporter.yaml'
      - './network_bitrate.sh:/network_bitrate.sh'
    command: '-f /edumeet-exporter.yaml'
